/**
 * V2 Bridge — connects the new V2 orchestrator to existing DB save patterns.
 * This bridges the gap until old generate-minutes.ts is fully retired.
 */
import {
  generateMinuteForAgendaV2,
  generateAllMinutesV2,
  loadMeetingContextV2,
  type AgendaGenerationResult,
} from './generate-minute-v2'
import { commitMinuteDraftToCurrentMinutesWithClient } from './generate-minutes'
import type { GenerateMinuteDraftPayload } from './types'
import type { DatabaseClient } from './shared'

// ── Convert V2 result → old draft payload for DB save ─────────────────

function toOldDraftPayload(result: AgendaGenerationResult): GenerateMinuteDraftPayload {
  return {
    content: result.content,
    sourceAgendaRevision: null,
    markers: [],
    appliedMemoryTrace: null,
    resolvedOutcomeMode: null,
    resolutionVariantKey: null,
    resolutionVariantLabel: null,
    resolutionVariantSource: null,
    resolutionExactRenderEnforced: false,
    prompt1Output: '',
    prompt2Output: '',
    summaryPaper: null,
    summaryDiscussion: null,
    summaryHeated: null,
  }
}

// ── Single agenda: generate + save ────────────────────────────────────

export async function generateAndSaveMinuteV2(params: {
  supabase: DatabaseClient
  meetingId: string
  agendaId: string
  userId: string
  organizationId: string
  transcriptId?: string | null
}): Promise<{ content: string; minuteId: string | null }> {
  const ctx = await loadMeetingContextV2(params.supabase, params.meetingId)
  const result = await generateMinuteForAgendaV2({
    supabase: params.supabase,
    ctx,
    agendaId: params.agendaId,
    transcriptId: params.transcriptId,
  })

  const minuteId = await commitMinuteDraftToCurrentMinutesWithClient({
    supabase: params.supabase,
    agendaId: params.agendaId,
    userId: params.userId,
    organizationId: params.organizationId,
    draft: toOldDraftPayload(result),
    changeSummary: 'Generated by V2 engine',
  })

  return { content: result.content, minuteId }
}

// ── Batch: generate all + save ────────────────────────────────────────

export async function generateAndSaveAllMinutesV2(params: {
  supabase: DatabaseClient
  meetingId: string
  userId: string
  organizationId: string
  transcriptId?: string | null
  concurrency?: number
}): Promise<{ saved: number; failed: number }> {
  const results = await generateAllMinutesV2({
    supabase: params.supabase,
    meetingId: params.meetingId,
    transcriptId: params.transcriptId,
    concurrency: params.concurrency,
  })

  let saved = 0
  let failed = 0

  for (const result of results) {
    try {
      await commitMinuteDraftToCurrentMinutesWithClient({
        supabase: params.supabase,
        agendaId: result.agendaId,
        userId: params.userId,
        organizationId: params.organizationId,
        draft: toOldDraftPayload(result),
        changeSummary: 'Generated by V2 engine (batch)',
      })
      saved++
    } catch (error) {
      console.error(`[V2 batch] Failed to save agenda ${result.agendaNo}:`, error)
      failed++
    }
  }

  return { saved, failed }
}
